version: "3.7"

# Use with docker/common.yaml
services:
  format_worker:
    image: image_processing_scala_format_worker
    depends_on:
      - rabbitmq
      - graphite
    volumes:
      - "../containers/format_worker/src:/app/src:ro"
      - "../containers/format_worker/build.sbt:/app/build.sbt:ro"
      - "../containers/format_worker/project/build.properties:/app/project/build.properties:ro"
      - "../containers/format_worker/project/plugins.sbt:/app/project/plugins.sbt:ro"
      - "~/.ivy2:/root/.ivy2:ro"
      - type: bind
        source: ../shared
        target: /app/shared
        read_only: false
    deploy:
      replicas: ${FORMAT_WORKER_REPLICAS}
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=format.worker_{{.Task.Slot}}

  resolution_worker:
    image: image_processing_scala_resolution_worker
    depends_on:
      - rabbitmq
      - graphite
    volumes:
      - "../containers/resolution_worker/src:/app/src"
      - "../containers/resolution_worker/build.sbt:/app/build.sbt"
      - "../containers/resolution_worker/project/build.properties:/app/project/build.properties"
      - "../containers/resolution_worker/project/plugins.sbt:/app/project/plugins.sbt"
      - "~/.ivy2:/root/.ivy2"
      - type: bind
        source: ../shared
        target: /app/shared
        read_only: false
    deploy:
      replicas: ${RESOLUTION_WORKER_REPLICAS}
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=resolution.worker_{{.Task.Slot}}

  size_worker:
    image: image_processing_scala_size_worker
    depends_on:
      - rabbitmq
      - graphite
    volumes:
      - "../containers/size_worker/src:/app/src"
      - "../containers/size_worker/build.sbt:/app/build.sbt"
      - "../containers/size_worker/project/build.properties:/app/project/build.properties"
      - "../containers/size_worker/project/plugins.sbt:/app/project/plugins.sbt"
      - "~/.ivy2:/root/.ivy2"
      - type: bind
        source: ../shared
        target: /app/shared
        read_only: false
    deploy:
      replicas: ${SIZE_WORKER_REPLICAS}
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=size.worker_{{.Task.Slot}}

  manager:
    image: image_processing_scala_manager
    depends_on:
      - rabbitmq
      - graphite
    volumes:
      - "../containers/manager/src/:/app/src"
      - "../containers/manager/build.sbt:/app/build.sbt"
      - "../containers/manager/project/build.properties:/app/project/build.properties"
      - "../containers/manager/project/plugins.sbt:/app/project/plugins.sbt"
      - "~/.ivy2:/root/.ivy2"
      - type: bind
        source: ../shared
        target: /app/shared
        read_only: false
    deploy:
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=manager